### ISSUE TITLE
При создании товара / вариации удалять wooms_id

### ISSUE THREAD

**Issue by OlaIola** [wpcraft-ru/wooms#409]
# todo 

- [ ] придумать кейс как повторить?
- [ ] перетащить код в класс про продукты
- [ ] wooms_id_check_if_unique - добавить проверку на продукт - чтобы другие посты не трогались
- [ ] протестировать локально

# notes
При копировании товара в новый товар - удалять wooms_id и другие связанные данные.
Возможная проблема - импорт данных с другого сайта, где wooms_id должен остаться, но другие связанные данные - под вопросом. Вероятно нужно проверять wooms_id на уникальность и оставлять, если значение уникальное.

**Comment by OlaIola** [comment]
![2021-05-02_17-45-12](https://user-images.githubusercontent.com/16874687/116821752-65ab8a00-ab7b-11eb-8b4e-b83b5b7b7642.png)
В случае когда wooms_id не уникален, эта строчка (ProductStocks.php:130) вызывает зацикливание, так как в зависимости от сортировки, получается не тот товар, который попал в выборку изначально.

**Comment by uptimizt** [comment]
не уверен что это пока можно вытянуть

правила такие - есть 1 источник правды о товарах - это МойСклад - товар должен быть там добавлен - а потом он может быть синхронизирован

копирование товаров на сайте - нарушает это правило

его обход возможен, но за отдельную плату
